# Args: <obj_file1> <obj_file2> <output_dir> <temp_dir>
{
  "version": 3,
  "setup": {
    "custom_blender_path": "C:/Program Files/Blender Foundation/Blender 2.83/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config": {
        "global": {
          "output_dir": "<args:2>",
          "temp_dir": "<args:3>"
        }
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:0>",
        "add_properties": {
           "cp_physics": True
        }
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:1>",
        "add_properties": {
          "cp_physics": False
        }
      }
    },
    {
      "module": "object.ObjectPoseSampler",
      "config":{
        "objects_to_sample": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_physics": True,
            "type": "MESH"
          }
        },
        "pos_sampler":{
          "provider":"sampler.Uniform3d",
          "max":[10, 10, 4],
          "min":[-10, -10, 30]
        },
        "rot_sampler":{
          "provider":"sampler.UniformSO3"
        }
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
          {
            "type": "SUN",
            "location": [0, 0, 0],
            "rotation": [-0.063, 0.6177, -0.1985],
            "energy": 1
          }
        ]
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "cam_poses": [
          {
            "location": [0, 0, 50],
            "rotation": {
              "value": [0, 0, 0]
            }
          }
        ]
      }
    },
    {
      "module": "object.PhysicsPositioning",
      "config": {
        "min_simulation_time": 4,
        "max_simulation_time": 20,
        "check_object_interval": 1,
        "collision_shape": "MESH"
      }
    },
    {
      "module": "renderer.RgbRenderer"
    }
  ]
}
