# Args:  <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "custom_blender_path": "C:/Program Files/Blender Foundation/Blender 2.83/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_is_temp": True,
          "temp_dir": "<args:0>",
          "resolution_x": 696,
          "resolution_y": 696,
          "for_animation": True,
          "animation_fps": 100,
          "animation_start": 0,
          "animation_end": 10
        }
      }
    },
    {
      "module": "constructor.GranulatumGenerator",
      "config":{
        "use_file": False,
        "keep_objects": True,
        "amount": 2200
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_generated": True
          }
        },
        "cp_physics": True
      }
    },
    {
      "module": "object.ObjectPoseSampler",
      "config":{
        "objects_to_sample": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_physics": True,
            "type": "MESH"
          }
        },
        "pos_sampler":{
          "provider":"sampler.Uniform3d",
          "max":[50, 20, 40],
          "min":[-20, -50, 20000]
        },
        "rot_sampler":{
          "provider":"sampler.UniformSO3"
        }
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "cam_poses": [
        {
          "location": [0, 250, 5],
          "rotation": {
            "value": [1.5707963268, 0, 3.1415926536]
          }
        },
        ]
      }
    },
    {
      "module": "lighting.LightLoader",
      "config": {
        "lights": [
        {
          "type": "SUN",
          "location": [0, 0, 0],
          "rotation": [-1.5707963268 ,0,0],
          "cast_shadow": False,
          "energy": 1
        }
        ]
      }
    },
    {
      "module": "object.PhysicsPositioning",
      "config": {
        "min_simulation_time": 10,
        "max_simulation_time": 11,
        "check_object_interval": 1,
        "keep_physics": True,
        "simulation_speed": 10,
        "collision_shape": "SPHERE"
      }
    },
    {
      "module": "renderer.RgbVideoRenderer",
      "config": {
        "samples": 20,
        "use_denoiser": False,
        "diffuse_bounces": 4,
        "glossy_bounces": 4,
        "max_bounces": 8,
        "transmission_bounces": 4,
        "transparency_bounces": 4,
        "simplify_subdivision_render": 0,
        "bvh_type": "DYNAMIC_BVH",
        "use_spatial_splits": False,
        "use_motion_blur": True,
        "motion_blur_shutter_speed": 0.3,
        "cf_change_gamma_color":{
          "gamma_color": [0.056498, 1.10824, 0.0]
        }
      }
    },
    {
      "module": "renderer.SimpleSegMapRenderer",
      "config": {
      }
    },
    {
      "module": "writer.MetaInformationWriter",
      "config": {
        "objects": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_physics": True
          }
        },
        "attributes_to_write": "cp_volume"
      }
    }
  ]
}