# Args:  <obj_file> <output_dir>
{
  "version": 3,
  "setup": {
    "custom_blender_path": "C:/Program Files/Blender Foundation/Blender 2.83/",
    "pip": [
      "h5py"
    ]
  },
  "modules": [
    {
      "module": "main.Initializer",
      "config":{
        "global": {
          "output_dir": "<args:1>"
        }
      }
    },
    {
      "module": "constructor.PelletGenerator",
      "config":{
        "use_file": False,
        "keep_objects": True,
        "amount": 400
      }
    },
    {
      "module": "loader.ObjectLoader",
      "config": {
        "path": "<args:0>",
        "add_properties": {
          "cp_physics": False
        }
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_generated": True
          }
        },
        "cp_physics": True
      }
    },
    {
      "module": "object.ObjectPoseSampler",
      "config":{
        "objects_to_sample": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_physics": True,
            "type": "MESH"
          }
        },
        "pos_sampler":{
          "provider":"sampler.Uniform3d",
          "max":[13, 13, 4],
          "min":[-13, -13, 100]
        },
        "rot_sampler":{
          "provider":"sampler.UniformSO3"
        }
      }
    },
    {
      "module": "manipulators.EntityManipulator",
      "config": {
        "selector": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_physics": False,
            "type": "MESH"
          }
        },
        "scale": [30, 4, 30],
        "hide_render": True
      }
    },
    {
      "module": "camera.CameraLoader",
      "config": {
        "cam_poses": [
        {
          "location": [0, 0, 13.35],
          "rotation": {
            "value": [0, 0, 0]
          }
        },
        {
          "location": [0, 2, 13.35],
          "rotation": {
            "value": [0, 0, 0]
          }
        }
        ]
      }
    },
    {
      "module": "object.PhysicsPositioning",
      "config": {
        "min_simulation_time": 14,
        "max_simulation_time": 15,
        "check_object_interval": 1,
        "collision_margin": 0.02,
        "update_object_poses": False,
        "objs_with_mesh_collision_shape": {
          "provider": "getter.Entity",
          "conditions": {
            "cp_physics": False
          }
        }
      }
    }
  ]
}
